### ISSUE TITLE
[DEFECT] CashFlowPlot indexing error from hatches

### ISSUE THREAD

**Issue by GabrielSoto-INL** [idaholab/TEAL#85]
--------
Defect Description
--------

**Describe the defect**
When plotting cashflows (here, via HERON) and there are more components than colormaps present, colormaps are recycled and hatch symbols are added to the new sequence. However, there was an indexing error when using a specific amount of extra components.

```
(  206.81 sec) HERON.DispatchPlot       : Message         -> Saved figure to "dispatch_id1_y2021_c8_SIGNAL.png"
(  209.93 sec) HERON.DispatchPlot       : Message         -> Saved figure 1/1 to "dispatch_id1_y2021_c9_f1.png"
(  211.69 sec) HERON.DispatchPlot       : Message         -> Saved figure to "dispatch_id1_y2021_c9_SIGNAL.png"
C:\Users\sotogj\projects\TEAL\src\CashFlowPlot.py:132: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  compColor += _rawCmapList[defaultEndColor:defaultStartColor:-(defaultEndColor-defaultStartColor)//compCount[i]]
C:\Users\sotogj\projects\TEAL\src\CashFlowPlot.py:138: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  compHatch.extend([None]*compCount[i])
Traceback (most recent call last):
  File "C:\Users\sotogj\AppData\Local\Miniconda3\envs\raven_libraries\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sotogj\AppData\Local\Miniconda3\envs\raven_libraries\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\sotogj\.vscode\extensions\ms-python.debugpy-2024.7.11591013-win32-x64\bundled\libs\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\sotogj\.vscode\extensions\ms-python.debugpy-2024.7.11591013-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\sotogj\.vscode\extensions\ms-python.debugpy-2024.7.11591013-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\sotogj\.vscode\extensions\ms-python.debugpy-2024.7.11591013-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\sotogj\.vscode\extensions\ms-python.debugpy-2024.7.11591013-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code       
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\sotogj\.vscode\extensions\ms-python.debugpy-2024.7.11591013-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:/Users/sotogj/projects/raven/raven_framework.py", line 25, in <module>
    sys.exit(main(True))
  File "C:\Users/sotogj/projects/raven\ravenframework\Driver.py", line 207, in main
    raven()
  File "C:\Users/sotogj/projects/raven\ravenframework\Driver.py", line 160, in raven
    simulation.run()
  File "C:\Users/sotogj/projects/raven\ravenframework\Simulation.py", line 901, in run
    self.executeStep(stepInputDict, stepInstance)
  File "C:\Users/sotogj/projects/raven\ravenframework\Simulation.py", line 834, in executeStep
    stepInstance.takeAstep(stepInputDict)
  File "C:\Users/sotogj/projects/raven\ravenframework\Steps\Step.py", line 317, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "C:\Users/sotogj/projects/raven\ravenframework\Steps\IOStep.py", line 264, in _localTakeAstepRun
    output.addOutput()
  File "C:\Users/sotogj/projects/raven\ravenframework\OutStreams\PlotEntity.py", line 102, in addOutput
    self._plotter.run()
  File "C:\Users\sotogj\projects\TEAL\src\CashFlowPlot.py", line 140, in run
    compHatch = pd.DataFrame(compHatch).set_axis([cumCashFlow.index.tolist()]).T
  File "C:\Users\sotogj\AppData\Local\Miniconda3\envs\raven_libraries\lib\site-packages\pandas\core\frame.py", line 5357, in set_axis
    return super().set_axis(labels, axis=axis, copy=copy)
  File "C:\Users\sotogj\AppData\Local\Miniconda3\envs\raven_libraries\lib\site-packages\pandas\core\generic.py", line 792, in set_axis
    return self._set_axis_nocheck(labels, axis, inplace=False, copy=copy)
  File "C:\Users\sotogj\AppData\Local\Miniconda3\envs\raven_libraries\lib\site-packages\pandas\core\generic.py", line 804, in _set_axis_nocheck
    setattr(obj, obj._get_axis_name(axis), labels)
  File "C:\Users\sotogj\AppData\Local\Miniconda3\envs\raven_libraries\lib\site-packages\pandas\core\generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\sotogj\AppData\Local\Miniconda3\envs\raven_libraries\lib\site-packages\pandas\core\generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\sotogj\AppData\Local\Miniconda3\envs\raven_libraries\lib\site-packages\pandas\core\internals\managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Users\sotogj\AppData\Local\Miniconda3\envs\raven_libraries\lib\site-packages\pandas\core\internals\base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 12 elements, new values have 13 elements
```

##### What did you expect to see happen?
This should have run successfully and produced cashflow plots.

##### What did you see instead?
Length mismatch error.

##### Do you have a suggested fix for the development team?
Looks like the hatch counting may pose an error if we are *not* on the first sequence of colormaps (i.e., we have just started using hatches) but reach a component with more than one cashflow. 
![image](https://github.com/idaholab/TEAL/assets/109242402/c005d6f5-1825-4193-8807-bc2582a381ae)

Here, the hatch symbol should be repeated per number of cashflows of component in the `for` loop.

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
Approved to close via #86
